# Deployment for my sample web on ns02 namespace.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpm02
  namespace: default
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: mypod
        image: nginx:latest
        resources:
          limits:
            cpu: "100m"
            memory: "32Mi"
        ports:
        - containerPort: 80