# Deployment for my sample web image on default namespace.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpm01
  namespace: default
  labels:
    app: test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      # nodeSelector:
      #   name: minikube
      containers:
      - name: mypod
        image: techwithnc/nodejs:1.0
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000