# Deployment for my sample web image on default namespace.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpm01
  namespace: default
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: mypod
        image: techwithnc/sampleweb:3.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80