# Deployment for my sample web on ns02 namespace.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpm02busybox
  namespace: default
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      nodeSelector:
        name: minikube
      containers:
      - name: mypod
        image: techwithnc/busybox:1.0
        resources:
          limits:
            cpu: "100m"
            memory: "32Mi"