# Deployment for my sample web image on default namespace.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpm04busybox
  namespace: default
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      nodeSelector:
        name: minikube-m02
      containers:
      - name: mypod
        image: techwithnc/busybox:1.0
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 80