# Deployment for my sample web image on ns02 namespace.


apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy202
  namespace: ns02
  labels:
    app: myweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: mypod
        image: techwithnc/sampleweb:1.0
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 80