apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy101
  namespace: ns01
  labels:
    lbl: lbl101
spec:
  replicas: 2
  selector:
    matchLabels:
      lbl: lbl101
  template:
    metadata:
      labels:
        lbl: lbl101
    spec:
      containers:
      - name: mypod
        image: techwithnc/sampleweb:1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80