# Deployment for creating Cluster IP on default namespace.

apiVersion: v1
kind: Service
metadata:
  name: mydb-service
  namespace: default
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80