# Deployment for creating NodePort service on default namespace

apiVersion: v1
kind: Service
metadata:
  name: svc02
  namespace: default
spec:
  type: NodePort
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 3000
      nodePort: 31000