# Deployment for creating Cluster IP on default namespace.

apiVersion: v1
kind: Service
metadata:
  name: svc01
  namespace: default
spec:
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 3000