apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy01
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: techwithnc/busybox:1.0
        command: ["sh", "-c", "sleep 4000"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
          - name: MY_NAME
            valueFrom:
              configMapKeyRef:
                name: cm01
                key: name
          - name: MY_DEPARTMENT
            valueFrom:
              configMapKeyRef:
                name: cm01
                key: department
          - name: MY_DOB
            valueFrom:
              configMapKeyRef:
                name: cm01
                key: dob
          - name: MY_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: cm01
                key: address
          - name: MY_WIFE_NAME
            valueFrom:
              configMapKeyRef:
                name: cm02
                key: name
          - name: MY_WIFE_DEPARTMENT
            valueFrom:
              configMapKeyRef:
                name: cm02
                key: department
          - name: MY_WIFE_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: cm02
                key: address
          - name: MY_SALARY
            valueFrom:
              secretKeyRef:
                name: secret01
                key: salary
          - name: MY_KEY
            valueFrom:
              secretKeyRef:
                name: secret01
                key: key
          - name: MY_TOKEN
            valueFrom:
              secretKeyRef:
                name: secret01
                key: token
          - name: MY_WIFE_SALARY
            valueFrom:
              secretKeyRef:
                name: secret02
                key: salary
          - name: MY_WIFE_KEY
            valueFrom:
              secretKeyRef:
                name: secret02
                key: key
          - name: MY_WIFE_TOKEN
            valueFrom:
              secretKeyRef:
                name: secret02
                key: token