apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpressdpm
  namespace: default
  labels:
    app: mongoexpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
      - name: mongoexpress
        image: mongo-express:latest
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1"
        ports:
        - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: cfm01
                key: mongodb-rul
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: sct01
                key: mongodbuser
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: sct01
                key: mongodbpassword
---

apiVersion: v1
kind: Service
metadata:
  name: mongoexpresssvc
spec:
  type: NodePort
  selector:
    app: mongoexpress
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000

