apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ns01
  name: pvc01
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
