# Deployment for my sample web image on default namespace.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpm01
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # nodeSelector:
      #   name: minikube
      containers:
      - name: mypod
        image: techwithnc/sampleweb:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 80