# Deployment for my sample web image on default namespace.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpm04
  namespace: default
  labels:
    app: test
spec:
  replicas: 
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: mypod
        image: nginx
        command: ['sh', '-c', "cat /home/file01/mydata.conf; cat /home/file02/companydata.conf; sleep 30"]
        volumeMounts:
          - mountPath: /home/file01
            name: vol01
          - name: vol02
            mountPath: /home/file02
            readOnly: true
        volumes:
        - name: vol01
          configMap:
            name: mydata.conf
        - name: vol02
          secret:
            secretName: companydata.conf
