# Deployment for my sample web image on default namespace.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpm03
  namespace: default
  labels:
    app: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      # nodeSelector:
      #   name: minikube
      containers:
      - name: mypod
        image: nginx
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        env:
        - name: MYNAME
          valueFrom:
            secretKeyRef:
              name: sct01
              key: name
        - name: MYDEPT
          valueFrom:
            secretKeyRef:
              name: sct01
              key: department
        - name: WORKNAME
          valueFrom:
            configMapKeyRef:
              name: cfm01
              key: company-name
        - name: WORKADDRESS
          valueFrom:
            configMapKeyRef:
              key: company-address
              name: cfm01