apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "100m"
      - name: log-sidecar
        image: busybox:1.28
        command: ['sh', '-c', "while true;do echo sysnc app logs; sleep 20; done"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
          requests:
            memory: "32Mi"
            cpu: "100m"
      initContainers:
        - name: initct01
          image: busybox:1.28
          command: ['sh', '-c', "until true; do echo init container is ok; sleep 4; done"]