apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpm01
  namespace: default
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /home/configmap01
            name: vol01
            readOnly: true
          - mountPath: /home/secret01
            name: vol02
            readOnly: true
      volumes:
        - name: vol01
          configMap:
            name: cfm01
            items:
              - key: "file01.txt"
                path: "01file.txt"
        - name: vol02
          secret:
            secretName: sct01
      
      

