apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpm01
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        command: ["sh", "-c"]
        args:
          - while true
              echo "$(date) INFO some app data" >> /var/log/myapp.log;
              sleep 5;
            done        
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/log
            name: vol01
      - name: log-sidecar
        image: busybox:1.28
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        command: ["sh", "-c"]
        args:
        - while true; do
            echo sync app logs;
            sleep 20;
          done;
        volumeMounts:
          - mountPath: /var/dir01
            name: vol01
      volumes:
        - name: vol01
          emptyDir: {}
      
