apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpm01
  namespace: default
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: NAME
            valueFrom:
              configMapKeyRef:
                name: cfm01
                key: name
          - name: ADDRESS
            valueFrom:
              configMapKeyRef:
                name: cfm01
                key: address
          - name: DEPARTMENT
            valueFrom:
              configMapKeyRef:
                name: cfm01
                key: department
          - name: BANK_ID
            valueFrom:
              secretKeyRef:
                name: sct01
                key: bank-id
          - name: SALARY
            valueFrom:
              secretKeyRef:
                name: sct01
                key: salary
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: sct01
                key: password
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: sct01
                key: token
          