apiVersion: v1
kind: Secret
metadata:
  name: sct01
type: Opaque
data:
  bank-id: VGhpcyBpcyBteSBiYW5rIGlkIG5v
  password: VGhpcyBpcyBteSBwYXNzd29yZA==
  salary: VGhpcyBpcyBteSBzYWxhcnk=
  token: VGhpcyBpcyBteSB0b2tlbg==